version: '2'
services:
  jhipsterimmo-app:
    image: jhipsterimmo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterimmo-postgresql:5432/jhipsterImmo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsterimmo-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsterimmo-elasticsearch:9200
    ports:
      - 8080:8080
  jhipsterimmo-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsterimmo-postgresql
  jhipsterimmo-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsterimmo-elasticsearch
