version: '2'
services:
  jhipsterimmo-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/jhipsterImmo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipsterImmo
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
